
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

pool:
  name: Default
steps:
- task: CmdLine@2
  displayName: 'Install KubeLinter'
  inputs:
    script: |
      curl -s https://api.github.com/repos/stackrox/kube-linter/releases/latest | grep "browser_download_url.*linux_amd64.tar.gz" | cut -d : -f 2,3 | tr -d \" | wget -qi -
      tar -xzf kube-linter-*.tar.gz
      sudo mv kube-linter /usr/local/bin/
      kube-linter version

- task: CmdLine@2
  displayName: 'Run KubeLinter Scan'
  inputs:
    script: |
      mkdir -p kubelinter-reports
      kube-linter lint frontend_manifests --format sarif --output kubelinter-reports/kubelinter-results.sarif

- task: PublishPipelineArtifact@1
  displayName: 'Publish KubeLinter Report'
  inputs:
    targetPath: 'kubelinter-reports'
    artifactName: 'kubelinter-reports'
