
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default


steps:
- script: |
    echo "Starting OWASP ZAP Docker container..."
    docker run -u zap -d --name zap -p 8080:8080 -p 8090:8090 -p 8091:8091 owasp/zap2docker-weekly zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true
    
    # Wait for ZAP to start
    echo "Waiting for OWASP ZAP to start..."
    sleep 60
    
    # Check if ZAP is running
    echo "Checking if OWASP ZAP is running..."
    docker ps -a
    
    # Run ZAP scan
    echo "Starting OWASP ZAP scan..."
    docker exec zap zap-cli quick-scan --self-contained http://your-service-external-ip:port
    
    # Copy the report out of the Docker container
    echo "Copying report from Docker container..."
    docker cp zap:/zap/wrk/zap_report.html $(Build.ArtifactStagingDirectory)/zap_report.html
    
    # Stop and remove the container
    echo "Stopping and removing OWASP ZAP Docker container..."
    docker stop zap
    docker rm zap
    
    # Check if the report is generated
    if [ -f "$(Build.ArtifactStagingDirectory)/zap_report.html" ]; then
        echo "Report generated successfully."
    else
        echo "Report not generated."
        exit 1
    fi
  displayName: 'Run OWASP ZAP Scan with Docker'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'zap-report'
    targetPath: '$(Build.ArtifactStagingDirectory)/zap_report.html'
  displayName: 'Publish OWASP ZAP Reports'