
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

pool:
  name: Default

steps:

- task: CmdLine@2
  displayName: 'DOWNLOAD AND INSTALL AQUASEC TRIVY'
  inputs:
    script: |
      sudo apt-get install wget apt-transport-https gnupg lsb-release
      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
      echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
      sudo apt-get update
      sudo apt-get install trivy
      trivy -v
      pwd
- task: CmdLine@2
  inputs:
      script: |
        trivy image --format table \
                    --output trivy-image-report.html \
                    hadil0505/hadil0505/haki_app:haki_finalll 