
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

jobs:
- job: BuildAndScan
  pool:
    name: Default
  steps:


  - script: |
      /usr/local/arachni/bin/arachni http://172.213.180.82/ --report-save-path=report.afr
    displayName: 'Run Arachni Scan'

  - script: |
      ls -la
    displayName: 'List files in working directory'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '/home/hadil/Desktop/myagent/_work/1/s/report.afr'
      artifact: 'arachni-report'
      publishLocation: 'pipeline'
    displayName: 'Publish Arachni Report'
