
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

pool:
  name: Default

steps:
- task: CmdLine@2
  displayName: 'Pull KubeLinter Docker Image'
  inputs:
    script: |
      docker pull stackrox/kube-linter:latest

- task: CmdLine@2
  displayName: 'Run KubeLinter Scan'
  inputs:
    script: |
      mkdir -p kubelinter-reports
      docker run --rm -v $(System.DefaultWorkingDirectory):/workdir stackrox/kube-linter:latest lint /workdir/frontend_manifests --format sarif --output /workdir/kubelinter-reports/kubelinter-results.sarif

- task: PublishPipelineArtifact@1
  displayName: 'Publish KubeLinter Report'
  inputs:
    targetPath: 'kubelinter-reports'
    artifactName: 'kubelinter-reports'
