
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

variables:
  frontendImageNameTag: 'front_final'
  dockerHubRepository: 'hadil0505/haki_app'

steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'


  - script: |
      sudo npm cache clear --force
      npm rm -rdf node_module
      sudo rm -rf package-lock.json
      npm install --force
 
    displayName: 'Clean npm Cache and Reinstall Dependencies'


  - task: Docker@2
    displayName: 'Build Frontend Docker Image'
    inputs:
      containerRegistry: 'dockerHub_connection'
      repository: '$(dockerHubRepository)'
      Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
      tags: |
        $(Build.BuildId)
        $(frontendImageNameTag)
  
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'kubernetes_connection'
      command: 'apply'
      useConfigurationFile: true
      configuration: 'frontend_manifests/frontend_deployment.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'