trigger:
- main

pool:
  name: Default
variables:
  zapDir: '$(Build.SourcesDirectory)/zap'
  reportHtml: '$(zapDir)/testreport.html'
  reportXml: '$(zapDir)/testreport.xml'
  reportJson: '$(zapDir)/testreport.json'
  targetUrl: 'http://172.213.180.82:80'

steps:
- script: |
    echo "Creating zap directory"
    mkdir -p $(zapDir)
  displayName: 'Create ZAP Directory'

- script: |
    echo "Setting permissions for zap directory"
    chmod -R 777 $(zapDir)
  displayName: 'Set Permissions'

- script: |
    echo "Running ZAP Baseline Scan"
    docker pull ghcr.io/zaproxy/zaproxy:stable
    docker run --rm -v $(zapDir):/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t $(targetUrl) -r /zap/wrk/testreport.html -x /zap/wrk/testreport.xml -J /zap/wrk/testreport.json -T 2
  displayName: 'Run ZAP Baseline Scan'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(zapDir)'
    ArtifactName: 'zap-reports'
    publishLocation: 'Container'
  displayName: 'Publish ZAP Reports'