
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main


jobs:
- job: BuildAndScan
pool:
  name: Default
  steps:
  - script: |
      wget https://github.com/arachni/arachni/releases/download/v1.5.0/arachni-1.5.0-0.3.11-20191203-linux-x86_64.tar.gz
      tar -xzf arachni-1.5.0-0.3.11-20191203-linux-x86_64.tar.gz
      sudo mv arachni-1.5.0-0.3.11 /usr/local/arachni
    displayName: 'Install Arachni'

  - script: |
      /usr/local/arachni/bin/arachni http://172.213.180.82/ --output-only-stdout --report-save-path=report.afr
    displayName: 'Run Arachni Scan'