
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

pool:
  name: Default

steps:
- script: |
    docker pull owasp/zap2docker-weekly
    docker run -u root -v $(System.DefaultWorkingDirectory):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-baseline.py -t <URL_TO_SCAN> -r zap_report.html
  displayName: 'Run OWASP ZAP Baseline Scan'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/zap_report.html'
    artifactName: 'DAST-Reports'
    publishLocation: 'pipeline'