
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

pool:
  name: Default

steps:
- task: CmdLine@2
  displayName: 'Install KubeLinter'
  inputs:
    script: |
      sudo apt-get update
      sudo apt-get install -y curl tar
      curl -L -o kube-linter-linux.tar.gz https://github.com/stackrox/kube-linter/releases/download/v0.6.8/kube-linter-linux.tar.gz
      tar -xzf kube-linter-linux.tar.gz
      sudo mv kube-linter /usr/local/bin/kube-linter
      rm kube-linter-linux.tar.gz

- task: CmdLine@2
  displayName: 'Run KubeLinter Scan'
  inputs:
    script: |
      mkdir -p kubelinter-reports
      kube-linter lint ./frontend_manifests > kubelinter-reports/kubelinter-results.txt

- task: PublishPipelineArtifact@1
  displayName: 'Publish KubeLinter Report'
  inputs:
    targetPath: 'kubelinter-reports'
    artifactName: 'kubelinter-reports'
