trigger:
- main

pool:
  name: Default

jobs:
- job: SecurityTest
  displayName: 'Security Test Job'
  pool:
    name: Default
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: 'hakiFrontend_pipeline'
      pipeline: 'hadilahmed05.web-framework-frontend'
      runVersion: 'latest'
      artifact: 'OWASPToNUnit3Artifact'
      downloadPath: '$(Pipeline.Workspace)/OWASPToNUnit3Artifact'

  - script: |
      echo "Listing contents of $(Pipeline.Workspace)"
      ls -R $(Pipeline.Workspace)
    displayName: 'List Workspace Directory'

  - script: |
      echo "Listing contents of $(Pipeline.Workspace)/OWASPToNUnit3Artifact"
      ls -R $(Pipeline.Workspace)/OWASPToNUnit3Artifact
    displayName: 'List contents of OWASPToNUnit3Artifact'

  - script: |
      echo "Checking contents of OWASP-ZAP-Report.xml"
      cat $(Pipeline.Workspace)/OWASP-ZAP-Report.xml
    displayName: 'Display OWASP-ZAP Report'

  - script: |
      xsltproc -o $(Pipeline.Workspace)/Converted-OWASP-ZAP-Report.xml $(Pipeline.Workspace)/OWASPToNUnit3Artifact/OWASPToNUnit3.xslt $(Pipeline.Workspace)/OWASP-ZAP-Report.xml
    displayName: 'Convert OWASP ZAP Report'

  - script: |
      echo "Checking contents of Converted-OWASP-ZAP-Report.xml"
      cat $(Pipeline.Workspace)/Converted-OWASP-ZAP-Report.xml
    displayName: 'Display Converted OWASP ZAP Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Pipeline.Workspace)/Converted-OWASP-ZAP-Report.xml'
      artifactName: 'ConvertedZAPReport'
