
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:
- checkout: self
  fetchDepth: 0

# Install Trivy
- script: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  displayName: 'Install Trivy'


# Run Trivy to scan the Docker image
- script: |
    trivy image --format json --output trivy-scan-result.json hadil0505/haki_app:haki_finalll
  displayName: 'Scan Docker Image with Trivy'

# Publish the scan result as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'trivy-scan-result.json'
    ArtifactName: 'TrivyScanResult'
    publishLocation: 'Container'
  displayName: 'Publish Trivy Scan Result'
