
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default


stages:
- stage: SecurityTest
  jobs:
  - job: RunSecurityTest
    displayName: 'Run OWASP ZAP Security Test'
    pool:
      name: Default
    steps:
    - script: |
        sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -I -j -t http://172.213.180.82:80 -x OWASP-ZAP-Report.xml -r testreport.html
      displayName: 'Run OWASP ZAP Scan'
    
    - script: |
        xsltproc -o Converted-OWASP-ZAP-Report.xml $SYSTEM_DEFAULTWORKINGDIRECTORY/_OWASP-Test/OWASPToNUnit3Artifact/OWASPToNUnit3.xslt OWASP-ZAP-Report.xml
      displayName: 'Convert OWASP ZAP Report'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '**/Converted-OWASP-ZAP-Report.xml'
        mergeTestResults: true
        failTaskOnFailedTests: true
        testRunTitle: 'OWASP ZAP Security Test Results'
      displayName: 'Publish OWASP ZAP Test Results'