trigger:
- main

pool:
  name: Default

jobs:
- job: SecurityTest
  displayName: 'Security Test Job'
  pool:
    name: Default
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: 'hakiFrontend_pipeline'
      pipeline: 'hadilahmed05.web-framework-frontend'
      runVersion: 'latest'
      artifact: 'OWASPToNUnit3Artifact'
      downloadPath: '$(Pipeline.Workspace)'

  - script: |
      echo "Listing contents of workspace"
      ls -R $(Pipeline.Workspace)
    displayName: 'List Workspace Directory'

  - script: |
      sudo docker run --rm -v $(Pipeline.Workspace):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -I -j -t http://172.213.180.82:80 -x OWASP-ZAP-Report.xml -r testreport.html
    displayName: 'Run OWASP ZAP Scan'

  - script: |
      xsltproc -o $(Pipeline.Workspace)/Converted-OWASP-ZAP-Report.xml $(Pipeline.Workspace)/OWASPToNUnit3Artifact/OWASPToNUnit3.xslt $(Pipeline.Workspace)/OWASP-ZAP-Report.xml
    displayName: 'Convert OWASP ZAP Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Pipeline.Workspace)/Converted-OWASP-ZAP-Report.xml'
      artifactName: 'ConvertedZAPReport'